name: DockerHub

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: pruiz/nomad-extip-manager
  DEFAULT_TAG: latest
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    name: build
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Versiona
        shell: pwsh
        run: |
          $runNumber = "${{ github.run_number }}"
          $commitHash = "${{ github.sha }}"
          $commitCount = (git rev-list --count HEAD)
          $version = "1.1.$commitCount.$runNumber"
          (Get-Content "Properties/AssemblyInfo.cs") -replace '0\.0\.0\.0', "$version" | Set-Content "Properties/AssemblyInfo.cs"
          (Get-Content "Properties/AssemblyInfo.cs") -replace 'GIT_COMMIT', "$commitHash" | Set-Content "Properties/AssemblyInfo.cs"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore dependencies
        run: nuget restore BasicAuth.Net.sln

      - name: Build
        run: msbuild /p:Configuration=Release BasicAuth.Net.sln

