name: DockerHub

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: pruiz/nomad-extip-manager
  DEFAULT_TAG: latest
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    name: build
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Calculate version
#        id: calculate_version
#        run: |
#          git fetch --all
#          GIT_REVNUM=$(git rev-list HEAD --count)
#          FIX_REVNUM=$(git rev-list origin/master..HEAD --count)
#          major=$(date -u +%y%j)
#          VERSION_TAG="${major}.${GIT_REVNUM:-0}.${FIX_REVNUM:-0}.${{ env.BUILD_NUMBER }}"
#          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore dependencies
        run: nuget restore BasicAuth.Net.sln

      - name: Build
        run: msbuild /p:Configuration=Release BasicAuth.Net.sln

